apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{application_name}}
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 8000
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /isAlive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  env:
    - name: CERT_PATH
      value: {{cert_path}}
    - name: REQUESTS_CA_BUNDLE
      value: {{cert_path}}
    - name: HTTPS_PROXY
      value: {{proxy}}
    - name: HTTP_PROXY
      value: {{proxy}}
    - name: https_proxy
      value: {{proxy}}
    - name: http_proxy
      value: {{proxy}}
    - name: NO_PROXY
      value: {{no_proxy}}
    - name: no_proxy
      value: {{no_proxy}}
    - name: partitionKey
      value: "type"
  ingresses:
    - {{ingress}}
    - {{ingress_nais_io}}
  leaderElection: false
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  istio:
    enabled: false
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
