apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ application_name }}
  namespace: {{ team }}
  labels:
    team: {{ team }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  azure:
    application:
      enabled: true
      replyURLs:
        - {{ azure_reply_url }}
  image: {{ image }}
  port: 8000
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /cosmosdb/isAlive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /cosmosdb/isReady
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  envFrom:
    - secret: cosmos-secret
  env:
    - name: AZURE_REPLY_URL
      value: {{ azure_reply_url }}
  ingresses:
    - {{ ingress }}
  leaderElection: false
  prometheus:
    enabled: true
    path: /cosmosdb/metrics
