apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ application_name }}
  namespace: {{ team }}
  labels:
    team: {{ team }}
spec:
  image: {{ image }}
  port: 8000
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /cosmosdb/isAlive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /cosmosdb/isReady
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  envFrom:
    - secret: cosmos-secret
  env:
    - name: INGRESS
      value: {{ ingress }}
  ingresses:
    - {{ ingress }}
  leaderElection: false
  prometheus:
    enabled: true
    path: /cosmosdb/metrics
