name: Build and deploy to dev-fss
on: push
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/data-catalog-api:${{ github.sha }}
jobs:
  build:
    name: build and push docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build and publish docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-dev:
    name: deploy to nais dev-fss cluster
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naisarator.yaml
          VARS: config-dev-fss.json

