name: Build and deploy to dev-gcp
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*.*'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}
jobs:
  build:
    name: build and push docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build and publish docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-dev-gcp:
    name: deploy to nais dev-gcp cluster
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: .nais/nais.yaml
        VARS: .nais/config-dev-gcp.json
